
function [cumVelTout,cumVelXout,cumVelYout,cumVelPout,cumVelMout, ...
  cumLenTout,cumLenXout,cumLenYout,cumLenPout,cumLenMout, ...
  hhgVelTout, hhgLenTout ] = ...
  DoFtStuffCore(...
  eFieldX, eFieldY, aFieldX, aFieldY, ...
  ftVelX, ftVelY, ftLenX, ftLenY, ...
  dTime,omega,doPlot,doPlot2,plotNum)

if nargout > 0 || doPlot
  [cumVelTout,cumVelXout,cumVelYout,cumVelPout,cumVelMout, ...
    cumLenTout,cumLenXout,cumLenYout,cumLenPout,cumLenMout ] = ...
    FourierAseCore(...
    eFieldX, eFieldY, aFieldX, aFieldY, ...
    ftVelX, ftVelY, ftLenX, ftLenY, ...
    dTime,omega,doPlot,plotNum);
end

if doPlot2
  [hhgVelTout,~,~,~,~, hhgLenTout] =  FourierHhgCore(...
    eFieldX, eFieldY, aFieldX, aFieldY, ...
    ftVelX, ftVelY, ftLenX, ftLenY, ...
    dTime,omega,doPlot2,plotNum);
end
end

